#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────
# Idswyft Community Edition — Install Script
# ─────────────────────────────────────────────────
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/team-idswyft/idswyft/main/install.sh | bash
#   or:
#   git clone https://github.com/team-idswyft/idswyft.git && cd idswyft && ./install.sh
# ─────────────────────────────────────────────────

REPO_URL="https://github.com/team-idswyft/idswyft.git"
BOLD="\033[1m"
CYAN="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}  ╔══════════════════════════════════════════╗${RESET}"
  echo -e "${CYAN}${BOLD}  ║     Idswyft Community Edition            ║${RESET}"
  echo -e "${CYAN}${BOLD}  ║     Identity Verification Platform       ║${RESET}"
  echo -e "${CYAN}${BOLD}  ╚══════════════════════════════════════════╝${RESET}"
  echo ""
}

info()  { echo -e "${CYAN}[INFO]${RESET}  $1"; }
ok()    { echo -e "${GREEN}[OK]${RESET}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${RESET}  $1"; }
fail()  { echo -e "${RED}[ERROR]${RESET} $1"; exit 1; }

# ─────────────────────────────────────────
# Pre-flight checks
# ─────────────────────────────────────────
check_dependencies() {
  info "Checking dependencies..."

  if ! command -v docker &>/dev/null; then
    fail "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
  fi

  if ! docker compose version &>/dev/null; then
    fail "Docker Compose V2 is required. Update Docker or install the compose plugin."
  fi

  if ! docker info &>/dev/null 2>&1; then
    fail "Docker daemon is not running. Start Docker and try again."
  fi

  ok "Docker and Docker Compose found"
}

# ─────────────────────────────────────────
# Clone repo if running via curl pipe
# ─────────────────────────────────────────
ensure_repo() {
  if [ ! -f "docker-compose.yml" ]; then
    info "Cloning Idswyft repository..."
    if ! command -v git &>/dev/null; then
      fail "Git is not installed. Install it from https://git-scm.com/"
    fi
    git clone "$REPO_URL" idswyft
    cd idswyft
    ok "Repository cloned"
  else
    ok "Already in Idswyft directory"
  fi
}

# ─────────────────────────────────────────
# Generate secrets
# ─────────────────────────────────────────
generate_secret() {
  # Generate a random 32-character hex string
  if command -v openssl &>/dev/null; then
    openssl rand -hex 16
  else
    head -c 16 /dev/urandom | xxd -p 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 32
  fi
}

# ─────────────────────────────────────────
# Create .env file
# ─────────────────────────────────────────
setup_env() {
  if [ -f ".env" ]; then
    warn ".env file already exists"
    read -rp "  Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      ok "Keeping existing .env"
      return
    fi
  fi

  info "Generating secure secrets..."

  local db_password
  local jwt_secret
  local api_key_secret
  local encryption_key
  local service_token

  db_password=$(generate_secret)
  jwt_secret=$(generate_secret)
  api_key_secret=$(generate_secret)
  encryption_key=$(generate_secret)
  service_token=$(generate_secret)

  cat > .env <<EOF
# ─────────────────────────────────────────
# Idswyft Community Edition Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# ─────────────────────────────────────────

# Database
DB_PASSWORD=${db_password}

# Authentication secrets (auto-generated, keep private)
JWT_SECRET=${jwt_secret}
API_KEY_SECRET=${api_key_secret}
ENCRYPTION_KEY=${encryption_key}
SERVICE_TOKEN=${service_token}

# Port to expose the frontend (default: 80)
PORT=80

# Set to true to enable sandbox/mock verification mode
SANDBOX_MODE=false
EOF

  ok "Created .env with secure secrets"
}

# ─────────────────────────────────────────
# Build and start
# ─────────────────────────────────────────
start_services() {
  info "Building containers (this may take a few minutes on first run)..."
  docker compose build --quiet

  info "Starting services..."
  docker compose up -d

  # Wait for health check
  info "Waiting for API to be ready..."
  local retries=0
  local max_retries=30
  while [ $retries -lt $max_retries ]; do
    if docker compose exec -T api wget -qO- http://localhost:3001/health &>/dev/null 2>&1; then
      break
    fi
    retries=$((retries + 1))
    sleep 2
  done

  if [ $retries -eq $max_retries ]; then
    warn "API health check timed out. Check logs with: docker compose logs api"
  else
    ok "API is healthy"
  fi
}

# ─────────────────────────────────────────
# Print success
# ─────────────────────────────────────────
print_success() {
  local port
  port=$(grep -E "^PORT=" .env 2>/dev/null | cut -d= -f2 || echo "80")

  echo ""
  echo -e "${GREEN}${BOLD}  ══════════════════════════════════════════${RESET}"
  echo -e "${GREEN}${BOLD}   Idswyft is running!${RESET}"
  echo -e "${GREEN}${BOLD}  ══════════════════════════════════════════${RESET}"
  echo ""
  echo -e "  ${BOLD}Dev Portal:${RESET}  http://localhost:${port}"
  echo -e "  ${BOLD}API:${RESET}         http://localhost:${port}/api"
  echo -e "  ${BOLD}API Docs:${RESET}    http://localhost:${port}/docs"
  echo -e "  ${BOLD}Demo:${RESET}        http://localhost:${port}/demo"
  echo ""
  echo -e "  ${BOLD}Useful commands:${RESET}"
  echo "    docker compose logs -f        # View logs"
  echo "    docker compose stop           # Stop services"
  echo "    docker compose up -d          # Start services"
  echo "    docker compose down           # Stop and remove containers"
  echo "    docker compose down -v        # Stop, remove containers and data"
  echo ""
  echo -e "  ${BOLD}Documentation:${RESET} https://idswyft.app/docs"
  echo -e "  ${BOLD}GitHub:${RESET}        https://github.com/team-idswyft/idswyft"
  echo ""
}

# ─────────────────────────────────────────
# Main
# ─────────────────────────────────────────
main() {
  banner
  check_dependencies
  ensure_repo
  setup_env
  start_services
  print_success
}

main "$@"
