import React from 'react';
import { AbsoluteFill, Audio, Sequence, Series, staticFile, useCurrentFrame, interpolate } from 'remotion';
import { TitleScene } from './components/dev/TitleScene';
import { RegisterScene } from './components/dev/RegisterScene';
import { CodeIntegrationScene } from './components/dev/CodeIntegrationScene';
import { VerificationInAction } from './components/dev/VerificationInAction';
import { DashboardScene } from './components/dev/DashboardScene';
import { CTAScene } from './components/dev/CTAScene';
import { C } from '../theme';

/**
 * Audio files for each scene. Generated by scripts/generate-narration.mjs
 * using ElevenLabs. Set `narration` prop to true once files are generated.
 */
const NARRATION_FILES = [
  'narration/scene-1-title.mp3',
  'narration/scene-2-register.mp3',
  'narration/scene-3-code.mp3',
  'narration/scene-4-verification.mp3',
  'narration/scene-5-dashboard.mp3',
  'narration/scene-6-cta.mp3',
];

/** Background music segments (~22s each, sequenced across the video) */
const BG_MUSIC = [
  { file: 'narration/bg-music-1.mp3', startFrame: 0,    durationFrames: 660 },
  { file: 'narration/bg-music-2.mp3', startFrame: 660,  durationFrames: 660 },
  { file: 'narration/bg-music-3.mp3', startFrame: 1320, durationFrames: 660 },
  { file: 'narration/bg-music-4.mp3', startFrame: 1980, durationFrames: 300 },
];

/**
 * DeveloperIntegrationDemo — Root Remotion composition
 *
 * 2190 frames total at 30fps (73s).
 *
 * Scene breakdown:
 *   Scene 1 - Title:              90 frames  ( 3.0s)
 *   Scene 2 - Register:          150 frames  ( 5.0s)
 *   Scene 3 - Code Integration: 1260 frames  (42.0s) — tutorial w/ cursor + keyboard FX
 *   Scene 4 - Verification:      300 frames  (10.0s)
 *   Scene 5 - Dashboard:         180 frames  ( 6.0s)
 *   Scene 6 - CTA:               210 frames  ( 7.0s)
 *
 * Total: 2190 frames = 73s at 30fps
 */

const FADE_DURATION = 15;

const SceneWrapper: React.FC<{
  children: React.ReactNode;
  durationInFrames: number;
  narrationSrc?: string;
}> = ({ children, durationInFrames, narrationSrc }) => {
  const frame = useCurrentFrame();

  const fadeIn = interpolate(frame, [0, FADE_DURATION], [0, 1], {
    extrapolateRight: 'clamp',
  });
  const fadeOut = interpolate(
    frame,
    [durationInFrames - FADE_DURATION, durationInFrames],
    [1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' },
  );

  return (
    <AbsoluteFill style={{ opacity: Math.min(fadeIn, fadeOut) }}>
      {narrationSrc && <Audio src={staticFile(narrationSrc)} volume={0.9} />}
      {children}
    </AbsoluteFill>
  );
};

interface DemoProps {
  /** Enable narration + background audio. Set to true after generating audio files. */
  narration?: boolean;
}

export const DeveloperIntegrationDemo: React.FC<DemoProps> = ({ narration = false }) => {
  const scenes: { frames: number; narration: string; content: React.ReactNode }[] = [
    { frames: 90,   narration: NARRATION_FILES[0], content: <TitleScene /> },
    { frames: 150,  narration: NARRATION_FILES[1], content: <RegisterScene /> },
    { frames: 1260, narration: NARRATION_FILES[2], content: <CodeIntegrationScene /> },
    { frames: 300,  narration: NARRATION_FILES[3], content: <VerificationInAction /> },
    { frames: 180,  narration: NARRATION_FILES[4], content: <DashboardScene /> },
    { frames: 210,  narration: NARRATION_FILES[5], content: <CTAScene /> },
  ];

  return (
    <AbsoluteFill style={{ background: C.bg }}>
      {/* Background music — low volume, layered under narration */}
      {narration &&
        BG_MUSIC.map((seg, i) => (
          <Sequence key={`bg-${i}`} from={seg.startFrame} durationInFrames={seg.durationFrames}>
            <Audio src={staticFile(seg.file)} volume={0.12} />
          </Sequence>
        ))}

      {/* Scene sequence */}
      <Series>
        {scenes.map((scene, i) => (
          <Series.Sequence key={i} durationInFrames={scene.frames}>
            <SceneWrapper
              durationInFrames={scene.frames}
              narrationSrc={narration ? scene.narration : undefined}
            >
              {scene.content}
            </SceneWrapper>
          </Series.Sequence>
        ))}
      </Series>
    </AbsoluteFill>
  );
};
